name: Generate pacman animation

on:
  schedule:
    - cron: '0 */12 * * *'  # A cada 12h
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Gerar pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Listar arquivos gerados (debug)
        run: ls -la

      - name: Criar diretório dist e mover SVG
        run: |
          mkdir -p dist
          mv pacman-contribution-graph*.svg dist/

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
